mavenlink/mavenlink_gem

- lib/config/specification.yml
Add to the list of `create_attributes` and `update_attributes` for workspaces specification file.
> Updating workspaces specification to include additional attributes 

- lib/config/specification.yml
This PR will allow the creation of nested substories along with the root.
> Substory Creation

- lib/mavenlink/client.rb
- mavenlink.gemspec
This would allow us to pass a custom client name so we can identify our own traffic.
ie: https://github.com/mavenlink-solutions/konekti/pull/856
> add user agent option

- lib/config/specification.yml
> Add Primary Maven

- lib/config/specification.yml
This P.R. adds expense categories for expenses to the gem spec file.
> Add expenses category id to create and update

- lib/config/specification.yml
- lib/mavenlink/role.rb
- spec/lib/mavenlink/role_spec.rb
This PR updates role attributes and adds a spec for the model.
> Update role attributes

- lib/config/specification.yml
- spec/lib/mavenlink/time_entry_spec.rb
This PR adds the `location` attribute to time entries.
> Add location to time entries

- lib/config/specification.yml
This PR fixes the active submission collection name for expenses.
> Fix Expense active submission collection

- lib/config/specification.yml
This P.R. adds timesheet submission association to time entries object.
> Add Timesheet Submission Association to Time Entries

- lib/config/specification.yml
Forgot to add this in #104 🤦‍♂️
> Add user_id to account memberships

- .circleci/config.yml
> add a circle config

- lib/config/specification.yml
- lib/mavenlink.rb
- lib/mavenlink/workspace_allocation.rb
- lib/mavenlink/workspace_resource.rb
- spec/lib/mavenlink/workspace_allocation_spec.rb
- spec/lib/mavenlink/workspace_resource_spec.rb
This PR adds two new models for `workspace_resources` and `workspace_allocations`.
> Add Workspace Resources & Workspace Allocations

- lib/config/specification.yml
- spec/lib/mavenlink/workspace_spec.rb
This PR adds all missing workspace associations.
> Add missing workspace associations

- lib/mavenlink/rate_card_set.rb
- spec/lib/mavenlink/rate_card_set_spec.rb
Add clone support to rate card set
We are also interested in thoughts on the message raised for a record not being persisted
> Add clone support to rate card set

- lib/config/specification.yml
Co-authored-by: Luke Walsh <lwalsh@mavenlink.com>
> add auto-update-label to update workspace resources

- lib/config/specification.yml
- spec/lib/mavenlink/workspace_allocation_spec.rb
Add creator, updater and workspace_id to workspace_allocations
> Update Workspace Allocations

- lib/config/specification.yml
Adds `amount_to_date` and `fees`.
> Update Project Accounting Records

- lib/config/specification.yml
Supports `external_references`
> Updated Custom Field Choices

- lib/config/specification.yml
Add foreign_exchange_amount as an attribute, create attribute, and update attribute to the expense endpoint
> Add Foreign Exchange Amount attribute to Expense

- lib/config/specification.yml
- [New MEA for Scheduled Hours to Time Entries](https://www.pivotaltracker.com/story/show/179502112)
blocked until this PR is merged
> add users ids to access groups

- lib/config/specification.yml
follower_id is an alias of user_id
> add follower_id instead of user_id to story follows

- lib/config/specification.yml
- spec/lib/mavenlink/status_report_spec.rb
> Add external references to status reports

- lib/config/specification.yml
[Add invoice association foreign key attributes](https://www.pivotaltracker.com/n/projects/2534061/stories/181120095)
> Add invoice association foreign key attributes

- lib/config/specification.yml
enable in-line external reference creation/update
add spec to support bulk_create with external references included
> Add external references participations

- lib/config/specification.yml
Reverts mavenlink/mavenlink_gem#217
> Revert "add external references to invoices"

- lib/mavenlink/request.rb
- spec/lib/mavenlink/request_spec.rb
And add scope to all get/post/put calls.
> Add existing request scope when building a new model

- lib/config/specification.yml
Reverts mavenlink/mavenlink_gem#218
> Revert "Revert "add external references to invoices""

- lib/config/specification.yml
> add approver_ids to create/update attributes

- lib/config/specification.yml
Added time_adjustments to invoice attributes (create/update)
Added time_adjustment associations
> Added time_adjustments to invoice 

- lib/config/specification.yml
custom field sets, custom field values, participations, posts, rate cards, sads, surveys
> add external reference to associations for many objects

- mavenlink.gemspec
Downgrade faraday version to allow mavenlink gem to update on konekti
> test faraday downgrade version run

- lib/config/specification.yml
- `time_trackable`
- `require_notes_on_time_entries`
- `stage`
> Add missing workspace attributes

- mavenlink.gemspec
Allow faraday versions beyond 2.0.
> Loosen faraday version requirements

- lib/config/specification.yml
Create attributes for `cost_budget_in_cents`, `status`, and `project_plan`
Update attributes for `cost_budget_in_cents` and `status`
> Update story attributes
