mavenlink/mavenlink_gem

lib/config/specification.yml
These fields are not supported when updating workspaces.
=> Remove expense and time approval fields from workspace update

lib/mavenlink.rb
This removes the duplicate require for `external_reference`
As a note, there are 131 failing specs on master and they appear to have been there for awhile now. My assumption is that it's either due to local setup or missing env file because on CI, the specs are green: https://circleci.com/gh/mavenlink/mavenlink_gem/77
=> Remove duplicate require statement

lib/config/specification.yml
The field `access_level` was missing from the workspace attributes.
=> Add attributes 'access_level' to workspaces

lib/config/specification.yml
This PR updates the `adjustment_date` and `post_date` attributes to their new names (`original_date` and `posted_on_date`).
=> Update Time Adjustment attribute names

lib/config/specification.yml, spec/lib/mavenlink/custom_field_value_spec.rb
This PR adds the missing `display_value` and `can_edit` attributes to custom field values. It also adds a spec file for custom field values.
=> Custom field value updates

lib/config/specification.yml
adds external_status to the external_reference attributes in the mavenlink gem
=> add external_status to external_reference

lib/config/specification.yml
This PR adds some missing fields to CustomField `attributes`, `create_attributes`, and `update_attributes`
=> Add missing custom field attributes

lib/config/specification.yml
This PR adds the two attributes `disabled` and `account_id` to users.
It also removed `user_id` since that is no longer an attribute.
=> Add `disabled` and `account_id` to user attributes

lib/config/specification.yml
This P.R. adds `primary_maven_id` to workspaces attributes.
=> Add `primary_maven_id` to workspaces specification

lib/config/specification.yml, spec/lib/mavenlink/workspace_spec.rb
Adding this association breaks existing calls we have using `workspace.custom_field_values.each_page.entries.flatten`. I will come back and revisit updating this association and its existing uses, but in the meantime master should not have these breaking changes.
=> Remove workspace `custom_field_values` association

lib/config/specification.yml, spec/lib/mavenlink/timesheet_submission_spec.rb
The association is a has many relationship and should be plural.
=> Make Timesheet Submission External Reference association plural

lib/config/specification.yml
Adding workspace_id to additional items after updating the Mavenlink API to include the attribute.
=> Add `workspace_id` to Additional Items

lib/mavenlink/request.rb, spec/lib/mavenlink/request_spec.rb
This is a hotfix for a bug in Mavenlink where the api returns a payload
such as
```
{
"count": 1,
"results": [],
"custom_field_values": {},
"meta": {
"count": 1,
"page_count": 1,
"page_number": 1,
"page_size": 20
}
}
```
Since we are looking for 1 but we continually get none in return, we
manually break the loop if the current page has nothing regardless of
what the count says.
=> Fix infinite loop

mavenlink.gemspec
This PR updates the gemspec to allow later `activesupport` and `activemodel` versions.
=> Allow later active* gem versions

lib/mavenlink/rate_card_set_version.rb, spec/lib/mavenlink/rate_card_set_version_spec.rb
Update the Rate Card Set Version publish method to always raise an error and rename it to `publish!`. 
Currently it will only return false for certain cases and raise an error for other unhandled exceptions. 
This change will always raise an error, which is the expected behavior for the method in Konekti. 
The PR to update this method name change in Konekti is https://github.com/mavenlink/konekti/pull/1799
=> Update error handling for Rate Card Set Version publish method

lib/mavenlink/model.rb, spec/lib/mavenlink/model_spec.rb
When building a new record locally, the association specification is not
populated properly which prevents one from loading an association using
that same model. Ultimately this is something that should be fixed inside
of https://github.com/mavenlink/brainstem-adaptor
=> Fix @associations_specification initialization

lib/config/specification.yml, lib/mavenlink/rate_card_set_version.rb, spec/lib/mavenlink/rate_card_set_version_spec.rb
Co-authored-by: Kevin Cotugno <kcotugno@mavenlink.com>
This PR adds the missing `clone_id` create_attribute and the association foreign key attributes.
It also adds a `clone_version!` method to raise errors when cloning fails.
=> Update rate_card_set_version attributes and add `clone_version!`

lib/config/specification.yml, spec/lib/mavenlink/organization_membership_spec.rb
This PR adds organization membership `update_attributes`, including the new `primary` attribute.
It also backfills a missing spec for the organization membership model.
=> Update organization membership attributes

lib/mavenlink/story.rb, spec/lib/mavenlink/story_spec.rb
This PR specifies `all_on_account: true` when reloading a story to fetch associations. This allows reloading of stories in workspaces the user is not a participant in.
=> Specify all_on_account when reloading story associations

lib/mavenlink/model.rb, lib/mavenlink/request.rb, lib/mavenlink/response.rb, lib/mavenlink/story.rb, spec/lib/mavenlink/client_spec.rb, spec/lib/mavenlink/model_spec.rb, spec/lib/mavenlink/request_spec.rb, spec/lib/mavenlink/story_spec.rb, spec/lib/mavenlink/workspace_spec.rb
This PR adds support for `show` endpoints which allow us to fetch objects directly that may be typically hidden behind a specific filter needed when using `?only=` (for example, a story where `all_on_account: true` is required).
With `show` we can reliably reload models without having to worry about filters like `all_on_account`. There is still the need for some filters, though, so we will keep the previous `association_load_filters` (i.e. `show_deleted` is still required for `show`)
With this change also comes the addition of keeping the request scope on each model.
=> Fix model reloading and associations

lib/mavenlink.rb, lib/mavenlink/model.rb
We were seeing part of the scope shared across model instances. This PR solves this by `deep_dup`ing scope.
=> Call deep_dup on model scope

lib/mavenlink/model.rb, lib/mavenlink/request.rb, spec/lib/mavenlink/client_spec.rb, spec/lib/mavenlink/model_spec.rb, spec/lib/mavenlink/request_spec.rb, spec/lib/mavenlink/workspace_spec.rb
This reverts commit 7292d9cb77edbd8c9391da856a06b23340331302.
Turns out not all endpoints have a show action. With the addition of the scope preserving functionality, we should not loose much by undoing this.
=> Revert "Add show method to use object/id on endpoints"

lib/config/specification.yml, spec/lib/mavenlink/time_off_entry_spec.rb
Add External Reference as a Create/Update attribute and an association for Time Off Entries in the Mavenlink Gem
ASAP
=> Update Mavenlink Gem to reflect new External Reference Support

lib/mavenlink/model.rb
This allows us to properly cache associations from the initial response or look to the cache if it has been loaded before.
If the association is not in the response or in the cache then it will reload.
=> Update association reload logic to reload if not in response or cache

lib/config/specification.yml, spec/lib/mavenlink/expense_spec.rb, spec/lib/mavenlink/time_entry_spec.rb
Add the recent_submission association to the Time Entries endpoint
Add recent_submission_id to the attributes
=> add recent_submission association to time_entries

lib/mavenlink/model.rb, lib/mavenlink/request.rb, spec/lib/mavenlink/model_spec.rb, spec/lib/mavenlink/request_spec.rb
This PR adds bulk creation support to the `Request` model and `Model` base class.
Bulk creations post a plural collection name key with the value being an array of hashes of attributes. Currently this is only supported by a very small number of endpoints but it is written to generically work as new objects start supporting bulk creation.
=> Support bulk creation

lib/config/specification.yml
The preceding `-` results in wrapping the association specification hash into an array. 
This breaks things in brainstem-adaptor because it always expects a hash.
=> Fix broken association definitions

lib/mavenlink/request.rb, spec/lib/mavenlink/request_spec.rb
This can be beneficial over a GET with only when an endpoint requires an additional argument (i.e. workspace_id). The show request should work without the additional argument.
=> Add Request#show

lib/mavenlink/client.rb
Explicitly setting request to `:json` will add the appropriate Content-Type header _and_ automatically encode request bodies as json.
=> If using json, set request type to json

lib/mavenlink/workspace_allocation.rb, spec/lib/mavenlink/workspace_allocation_spec.rb
Allow split endpoint to be called on workspace alllocations through a PUT call.
=> Add Split Endpoint Call to Workspace Allocations

lib/config/specification.yml
Adding primary tag to use in conjunction with Flatfile SOW change along with other projects that use organization memberships.
=> Support Primary Tag on Create Attributes for Organization Memberships

mavenlink.gemspec
Capping the version keeps us from running into the spec errors shown in this PR [#12080](https://github.com/CocoaPods/CocoaPods/issues/12080)
=> Cap Active Support version to 7.0.8

lib/config/specification.yml
We are seeing some timeouts/500 error responses when fetching 10000 time entries per page. Fetching 5000 a page does not encounter the same issues.
=> Lower time entry per_page to 5000

lib/config/specification.yml
The following attributes are updatable but missing from the specification:
- `invoice_date`
- `tax_rate`
=> Add missing invoice update attributes

lib/config/specification.yml, lib/mavenlink.rb
Two new attributes:
- can_schedule_their_hours
- can_schedule_team_hours
One attribute is now settable on create (and was missing from read attributes):
- access_level
=> Update participation attributes
